import logoImg from "../assets/logo.png";

// Product Categories
export const PRODUCT_CATEGORIES = [
	{ id: "all", name: "All Products", icon: "🛍️" },
	{ id: "hookah", name: "Hookahs", icon: "🚬" },
	{ id: "vaping", name: "Vaping", icon: "💨" },
	{ id: "tobacco", name: "Tobacco", icon: "🍃" },
	{ id: "accessories", name: "Accessories", icon: "🔧" },
];

// All Products Data
export const PRODUCTS_DATA = [
	// --- Hookahs (7 products) ---
	{
		id: 1,
		name: "Traditional Hookah",
		category: "hookah",
		price: 89.99,
		image: "https://images.unsplash.com/photo-1694071049321-ca04e17d779d",
		description: "Classic traditional hookah with brass base",
		rating: 4.5,
		inStock: true,
		flavors: ["Apple", "Mint", "Grape", "Strawberry"],
		details: "Handcrafted brass hookah with traditional design. Includes hose, bowl, and base. Perfect for authentic smoking experience.",
		specifications: {
			Material: "Brass",
			Height: "24 inches",
			Weight: "2.5 kg",
			Includes: "Hose, Bowl, Base, Tongs",
			Warranty: "1 Year",
		},
	},
	{
		id: 2,
		name: "Modern Glass Hookah",
		category: "hookah",
		price: 149.99,
		image: "https://images.unsplash.com/photo-1694071049321-ca04e17d779d",
		description: "Contemporary glass hookah with LED lights",
		rating: 4.8,
		inStock: true,
		flavors: ["Blueberry", "Watermelon", "Pineapple", "Cherry"],
		details: "Modern glass hookah featuring LED lighting system. Includes premium hose and glass bowl. Perfect for parties and gatherings.",
		specifications: {
			Material: "Glass & Stainless Steel",
			Height: "28 inches",
			Weight: "3.2 kg",
			Includes: "LED Base, Premium Hose, Glass Bowl, Remote",
			Warranty: "2 Years",
		},
	},
	{
		id: 3,
		name: "Portable Hookah",
		category: "hookah",
		price: 69.99,
		image: "https://images.unsplash.com/photo-1694071049321-ca04e17d779d",
		description: "Compact travel-friendly hookah",
		rating: 4.2,
		inStock: false,
		flavors: ["Mint", "Lemon", "Orange"],
		details: "Compact and portable hookah perfect for travel. Easy to assemble and disassemble. Includes carrying case.",
		specifications: {
			Material: "Aluminum",
			Height: "18 inches",
			Weight: "1.8 kg",
			Includes: "Travel Case, Hose, Bowl, Base",
			Warranty: "6 Months",
		},
	},
	{
		id: 13,
		name: "Deluxe Double Hose Hookah",
		category: "hookah",
		price: 179.99,
		image: "https://images.unsplash.com/photo-1694071049321-ca04e17d779d",
		description: "Premium double hose hookah for shared sessions",
		rating: 4.9,
		inStock: true,
		flavors: ["Peach", "Mint", "Coconut", "Lemon"],
		details: "Large-sized hookah with dual hose system and elegant glass design. Built for durability and group sessions.",
		specifications: {
			Material: "Glass & Stainless Steel",
			Height: "32 inches",
			Weight: "4 kg",
			Includes: "2 Hoses, Bowl, Base, Tongs",
			Warranty: "2 Years",
		},
	},
	{
		id: 14,
		name: "Mini Cube Hookah",
		category: "hookah",
		price: 59.99,
		image: "https://images.unsplash.com/photo-1694071049321-ca04e17d779d",
		description: "Compact cube‑shaped hookah for modern use",
		rating: 4.4,
		inStock: true,
		flavors: ["Mango", "Cherry", "Berry"],
		details: "Stylish cube-shaped mini hookah with acrylic body and stainless steel fittings. Portable and easy to clean.",
		specifications: {
			Material: "Acrylic & Steel",
			Height: "16 inches",
			Weight: "1.5 kg",
			Includes: "Hose, Bowl, Base, Carry Bag",
			Warranty: "1 Year",
		},
	},
	{
		id: 15,
		name: "Premium Shisha Lounge Hookah",
		category: "hookah",
		price: 229.99,
		image: "https://images.unsplash.com/photo-1694071049321-ca04e17d779d",
		description: "High-end lounge style hookah for upscale ambiance",
		rating: 4.7,
		inStock: true,
		flavors: ["Vanilla", "Coffee", "Grape", "Mint"],
		details: "Luxury lounge-grade hookah with extra large base, decorative elements and premium components. Ideal for lounge or home party use.",
		specifications: {
			Material: "Brass & Glass",
			Height: "30 inches",
			Weight: "3.8 kg",
			Includes: "Premium Hose, Bowl, Base, Tongs, Carry Case",
			Warranty: "2 Years",
		},
	},
	{
		id: 16,
		name: "Eco-Friendly Bamboo Hookah",
		category: "hookah",
		price: 99.99,
		image: "https://images.unsplash.com/photo-1694071049321-ca04e17d779d",
		description: "Sustainable bamboo-based hookah with minimalist design",
		rating: 4.3,
		inStock: true,
		flavors: ["Lime", "Mint", "Watermelon"],
		details: "Eco-conscious hookah made with bamboo body and stainless steel components. Lightweight and stylish.",
		specifications: {
			Material: "Bamboo & Steel",
			Height: "22 inches",
			Weight: "2.2 kg",
			Includes: "Hose, Bowl, Base",
			Warranty: "1 Year",
		},
	},

	// --- Vaping (6 products) ---
	{
		id: 4,
		name: "Vape Pen Starter Kit",
		category: "vaping",
		price: 39.99,
		image: "https://images.unsplash.com/photo-1715613814395-6847f5b6e178",
		description: "Complete vaping starter kit for beginners",
		rating: 4.3,
		inStock: true,
		flavors: ["Tobacco", "Menthol", "Vanilla", "Coffee"],
		details: "Complete starter kit includes vape pen, charger, and 3 e-liquid bottles. Perfect for beginners.",
		specifications: {
			Battery: "650mAh",
			Capacity: "2ml",
			Includes: "Vape Pen, Charger, 3 E-liquids",
			Warranty: "1 Year",
		},
	},
	{
		id: 5,
		name: "Premium E-Liquid Set",
		category: "vaping",
		price: 24.99,
		image: "https://images.unsplash.com/photo-1605136647683-934bb94e42c7?auto=format&fit=crop&w=400&q=80",
		description: "Assorted premium e-liquid flavors",
		rating: 4.6,
		inStock: true,
		flavors: ["Strawberry", "Blueberry", "Mango", "Peach", "Watermelon"],
		details: "Premium e-liquid set with 5 different flavors. Each bottle contains 30ml of high-quality liquid.",
		specifications: {
			Volume: "30ml each",
			Nicotine: "0-18mg",
			"PG/VG": "30/70",
			Count: "5 bottles",
			Expiry: "2 years",
		},
	},
	{
		id: 6,
		name: "Vape Mod Device",
		category: "vaping",
		price: 79.99,
		image: "https://images.unsplash.com/photo-1610051071625-1bde334f620b?auto=format&fit=crop&w=400&q=80",
		description: "Advanced vaping mod with temperature control",
		rating: 4.7,
		inStock: true,
		flavors: ["Customizable", "Any flavor compatible"],
		details: "Advanced vaping mod with temperature control and variable wattage. Compatible with all e-liquids.",
		specifications: {
			Battery: "Dual 18650",
			Wattage: "200W max",
			Temperature: "100-315°C",
			Includes: "Mod, Tank, Coils",
			Warranty: "1 Year",
		},
	},
	{
		id: 17,
		name: "Pod System Vape",
		category: "vaping",
		price: 29.99,
		image: "https://images.unsplash.com/photo-1715613814395-6847f5b6e178",
		description: "Compact pod-style vape for on-the-go use",
		rating: 4.1,
		inStock: true,
		flavors: ["Menthol", "Tobacco", "Fruit Mix"],
		details: "Small yet powerful pod-style vape, perfect for beginners and travel.",
		specifications: {
			Battery: "500mAh",
			Capacity: "2ml",
			Includes: "Pod, Charger, 2 E-liquids",
			Warranty: "1 Year",
		},
	},
	{
		id: 18,
		name: "Advanced Box Mod Vape",
		category: "vaping",
		price: 129.99,
		image: "https://images.unsplash.com/photo-1715613814395-6847f5b6e178",
		description: "Powerful vaping device with digital display and temp control",
		rating: 4.8,
		inStock: true,
		flavors: ["Custom", "Any flavor compatible"],
		details: "Advanced digital mod for vapers who want precision and power. Supports all atomizers.",
		specifications: {
			Battery: "Dual 18650",
			Wattage: "250W max",
			Temperature: "100-315°C",
			Includes: "Mod, Tank, Coils, Charger",
			Warranty: "2 Years",
		},
	},
	{
		id: 19,
		name: "Vape Starter Kit Mini",
		category: "vaping",
		price: 29.99,
		image: "https://images.unsplash.com/photo-1715613814395-6847f5b6e178",
		description: "Mini starter kit for new vapers",
		rating: 4.2,
		inStock: true,
		flavors: ["Mint", "Vanilla", "Berry"],
		details: "Compact mini starter kit with one pod and one e-liquid bottle.",
		specifications: {
			Battery: "350mAh",
			Capacity: "1.5ml",
			Includes: "Pod, Charger, E-liquid",
			Warranty: "6 Months",
		},
	},

	// --- Tobacco (6 products) ---
	{
		id: 7,
		name: "Premium Tobacco Blend",
		category: "tobacco",
		price: 12.99,
		image: "https://images.unsplash.com/photo-1632094183960-266df564e674",
		description: "Handcrafted premium tobacco blend",
		rating: 4.4,
		inStock: true,
		flavors: ["Virginia", "Burley", "Oriental", "Cavendish"],
		details: "Handcrafted premium tobacco blend made from the finest leaves. Available in 50g and 100g packages.",
		specifications: {
			Weight: "50g/100g",
			Origin: "Multiple regions",
			Cut: "Fine cut",
			Moisture: "Optimal",
			Storage: "Airtight container",
		},
	},
	{
		id: 8,
		name: "Rolling Papers Pack",
		category: "tobacco",
		price: 4.99,
		image: "https://images.unsplash.com/photo-1610051071625-1bde334f620b?auto=format&fit=crop&w=400&q=80",
		description: "High-quality rolling papers (50 sheets)",
		rating: 4.1,
		inStock: true,
		flavors: ["Natural", "Hemp", "Rice", "Flax"],
		details: "High-quality rolling papers available in different materials. Each pack contains 50 sheets.",
		specifications: {
			Count: "50 sheets",
			Size: "1.25 inch",
			Material: "Various",
			Thickness: "Ultra-thin",
			Bleaching: "Natural",
		},
	},
	{
		id: 9,
		name: "Tobacco Filters",
		category: "tobacco",
		price: 6.99,
		image: "https://images.unsplash.com/photo-1632094183960-266df564e674",
		description: "Premium tobacco filters (100 count)",
		rating: 4.0,
		inStock: true,
		flavors: ["Activated charcoal", "Cotton", "Cellulose"],
		details: "Premium tobacco filters available in different materials. Each pack contains 100 filters.",
		specifications: {
			Count: "100 filters",
			Size: "6mm",
			Material: "Various",
			Length: "15mm",
			Filtration: "High efficiency",
		},
	},
	{
		id: 20,
		name: "Flavored Tobacco Mix",
		category: "tobacco",
		price: 15.99,
		image: "https://images.unsplash.com/photo-1632094183960-266df564e674",
		description: "Assorted flavored tobacco blend",
		rating: 4.5,
		inStock: true,
		flavors: ["Apple", "Mint", "Cherry", "Vanilla"],
		details: "Assorted flavored tobacco blend perfect for rolling or pipe smoking.",
		specifications: {
			Weight: "50g",
			Origin: "Local farms",
			Cut: "Fine",
			Moisture: "Optimal",
			Storage: "Airtight",
		},
	},
	{
		id: 21,
		name: "Smoking Pipe Kit",
		category: "tobacco",
		price: 29.99,
		image: "https://images.unsplash.com/photo-1632094183960-266df564e674",
		description: "Complete smoking pipe kit",
		rating: 4.6,
		inStock: true,
		flavors: ["Wood", "Briar", "Cherry"],
		details: "Complete pipe kit including wooden pipe, filters, and tobacco pouch.",
		specifications: {
			Includes: "Pipe, Filters, Pouch",
			Material: "Briar & Wood",
			Weight: "200g",
			Warranty: "6 Months",
		},
	},
	{
		id: 22,
		name: "Tobacco Storage Box",
		category: "tobacco",
		price: 34.99,
		image: "https://images.unsplash.com/photo-1632094183960-266df564e674",
		description: "Airtight tobacco storage box",
		rating: 4.7,
		inStock: true,
		flavors: ["Wood", "Plastic", "Glass"],
		details: "Preserve tobacco freshness in airtight storage box.",
		specifications: {
			Material: "Wood & Glass",
			Capacity: "500g",
			Seal: "Airtight",
			Features: "UV protection",
		},
	},

	// --- Accessories (6 products) ---
	{
		id: 10,
		name: "Premium Lighter",
		category: "accessories",
		price: 19.99,
		image: "https://images.unsplash.com/photo-1576682631235-90941f11cf04",
		description: "Windproof premium lighter",
		rating: 4.5,
		inStock: true,
		flavors: ["Butane", "Electric", "Plasma"],
		details: "Windproof premium lighter with adjustable flame. Available in different fuel types.",
		specifications: {
			Fuel: "Butane",
			Capacity: "12ml",
			Flame: "Adjustable",
			Windproof: "Yes",
			Warranty: "1 Year",
		},
	},
	{
		id: 11,
		name: "Glass Ashtray",
		category: "accessories",
		price: 14.99,
		image: "https://images.unsplash.com/photo-1576682631235-90941f11cf04",
		description: "Elegant glass ashtray with holder",
		rating: 4.2,
		inStock: true,
		flavors: ["Clear", "Smoked", "Colored"],
		details: "Elegant glass ashtray with built-in holder. Available in different colors and finishes.",
		specifications: {
			Material: "Glass",
			Diameter: "6 inches",
			Height: "2 inches",
			Features: "Built-in holder",
			Care: "Hand wash",
		},
	},
	{
		id: 12,
		name: "Tobacco Storage Jar",
		category: "accessories",
		price: 29.99,
		image: "https://images.unsplash.com/photo-1576682631235-90941f11cf04",
		description: "Airtight tobacco storage jar",
		rating: 4.6,
		inStock: false,
		flavors: ["Glass", "Ceramic", "Metal"],
		details: "Airtight tobacco storage jar to preserve freshness. Available in different materials and sizes.",
		specifications: {
			Material: "Glass",
			Capacity: "250ml",
			Seal: "Airtight",
			Features: "UV protection",
			Care: "Dishwasher safe",
		},
	},
	{
		id: 23,
		name: "Hookah Tongs",
		category: "accessories",
		price: 9.99,
		image: "https://images.unsplash.com/photo-1576682631235-90941f11cf04",
		description: "Stainless steel hookah tongs",
		rating: 4.3,
		inStock: true,
		flavors: [],
		details: "Durable stainless steel hookah tongs for safe handling of charcoal and coals.",
		specifications: {
			Material: "Stainless Steel",
			Length: "10 inches",
			Care: "Hand wash",
		},
	},
	{
		id: 24,
		name: "Charcoal Burner",
		category: "accessories",
		price: 39.99,
		image: "https://images.unsplash.com/photo-1576682631235-90941f11cf04",
		description: "Electric charcoal burner for hookah",
		rating: 4.5,
		inStock: true,
		flavors: [],
		details: "Quickly light hookah charcoal with this compact electric burner.",
		specifications: {
			Power: "600W",
			Voltage: "220V",
			Includes: "Burner, Stand",
			Warranty: "1 Year",
		},
	},
	{
		id: 25,
		name: "Hookah Cleaning Brush Set",
		category: "accessories",
		price: 14.99,
		image: "https://images.unsplash.com/photo-1576682631235-90941f11cf04",
		description: "Complete brush set for hookah cleaning",
		rating: 4.4,
		inStock: true,
		flavors: [],
		details: "Includes brushes for pipe, hose, and base cleaning. Essential for maintaining hookah hygiene.",
		specifications: {
			Includes: "3 Brushes",
			Material: "Nylon & Plastic",
			Care: "Rinse after use",
		},
	},
];

// Featured Section Data
export const FEATURED_SECTION_DATA = [
	{
		icon: "FaShieldAlt",
		title: "Quality Products",
		description: "We offer reliable tobacco products and accessories that meet your smoking needs with consistent quality standards",
		gradient: "from-amber-400 to-orange-500",
	},
	{
		icon: "FaStar",
		title: "Good Selection",
		description: "Browse through our variety of hookahs, vaping products, tobacco, and smoking accessories in one place",
		gradient: "from-yellow-400 to-amber-500",
	},
	{
		icon: "FaHandshake",
		title: "Friendly Service",
		description: "Get helpful advice and recommendations from our knowledgeable staff to find the right products for you",
		gradient: "from-red-400 to-pink-500",
	},
	{
		icon: "FaUsers",
		title: "Local Shop",
		description: "Support your local tobacco shop with personalized service and community-focused business approach",
		gradient: "from-gray-400 to-gray-600",
	},
];

// Product Showcase Data
export const PRODUCT_SHOWCASE_DATA = [
	{
		id: "hookah",
		title: "Hookah Collection",
		description: "Quality hookahs and accessories for your smoking experience",
		image: "https://images.unsplash.com/photo-1630175772812-3368aad7982d",
		gradient: "from-amber-400 to-orange-500",
		features: ["Traditional Hookahs", "Modern Designs", "Accessories"],
	},
	{
		id: "vaping",
		title: "Vaping Products",
		description: "Vaping devices, e-liquids, and replacement parts",
		image: "https://images.unsplash.com/photo-1545095088-26a59e3f2717",
		gradient: "from-red-400 to-pink-500",
		features: ["Vape Devices", "E-Liquids", "Coils & Parts"],
	},
	{
		id: "tobacco",
		title: "Tobacco Products",
		description: "Various tobacco blends and smoking accessories",
		image: "https://images.unsplash.com/photo-1580044305912-70d6e42062cc",
		gradient: "from-yellow-400 to-amber-500",
		features: ["Tobacco Blends", "Rolling Papers", "Filters"],
	},
	{
		id: "accessories",
		title: "Smoking Accessories",
		description: "Essential accessories for tobacco and smoking enthusiasts",
		image: "https://images.unsplash.com/photo-1576682631235-90941f11cf04",
		gradient: "from-gray-400 to-gray-600",
		features: ["Lighters", "Ashtrays", "Storage"],
	},
	{
		id: "limited",
		title: "Limited Editions",
		description: "Rare and seasonal smoking products with exclusive designs and flavors",
		image: "https://images.unsplash.com/photo-1685003227041-49af807c0113",
		gradient: "from-purple-500 to-indigo-500",
		features: ["Rare Hookahs", "Seasonal E-liquids", "Collector Accessories"],
	},
	{
		id: "newarrivals",
		title: "New Arrivals",
		description: "Fresh arrivals and trending products in the smoking world",
		image: "https://images.unsplash.com/photo-1625125875922-dd44b1ec9b1f",
		gradient: "from-green-400 to-emerald-500",
		features: ["Modern Hookahs", "Upgraded Vape Mods", "Stylish Lighters"],
	},
];

// Footer Data
export const FOOTER_DATA = {
	quickLinks: [
		{ name: "Home", path: "/" },
		{ name: "Products", path: "/products" },
		{ name: "About Us", path: "/about" },
		{ name: "Contact", path: "/contact" },
	],
	productCategories: [
		{ name: "Hookahs", path: "/products?category=hookah" },
		{ name: "Vaping", path: "/products?category=vaping" },
		{ name: "Tobacco", path: "/products?category=tobacco" },
		{ name: "Accessories", path: "/products?category=accessories" },
	],
	businessHours: [
		{ day: "Saturday - Sunday", hours: "10:00 AM - 10:00 PM" },
		{ day: "Monday - Tuesday", hours: "10:00 AM - 08:00 PM" },
		{ day: "Wednesday - Friday", hours: "10:00 AM - 10:00 PM" },
	],
	socialLinks: [
		{ name: "Facebook", icon: "FaFacebook", url: "#", color: "hover:text-blue-500" },
		{ name: "Instagram", icon: "FaInstagram", url: "#", color: "hover:text-pink-500" },
		{ name: "Twitter", icon: "FaTwitter", url: "#", color: "hover:text-blue-400" },
		{ name: "WhatsApp", icon: "FaWhatsapp", url: "#", color: "hover:text-green-500" },
	],
	contactInfo: {
		phone: "+1 (859)-608-1400",
		email: "-",
		address: {
			street: "537 Waller Ave",
			city: "Lexington, KY, 40504",
		},
	},
};

// Navigation Data
export const NAVIGATION_DATA = [
	{ to: "/", text: "Home" },
	{ to: "/products", text: "All Products" },
	{ to: "/contact", text: "Contact" },
];

// Company Information
export const COMPANY_INFO = {
	name: "Tobacco N Things",
	description: "Your local tobacco shop offering quality products, friendly service, and a wide selection of smoking accessories.",
	logo: logoImg,
};
